<a href="https://www.kaggle.com/shivavashishtha/notebook47aa9d3072?scriptVersionId=89781900" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/2022-ipl-auction-dataset/ipl_2022_dataset.csv

# Importing the Dataframe

In [2]:
df=pd.read_csv("../input/2022-ipl-auction-dataset/ipl_2022_dataset.csv",index_col="Unnamed: 0")

In [3]:
df

,Player,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad,Team
0,Rashid Khan,Draft Pick,BOWLER,15.0,1950.0,SRH,Gujarat Titans
1,Hardik Pandya,Draft Pick,ALL-ROUNDER,15.0,1950.0,MI,Gujarat Titans
2,Lockie Ferguson,2 Cr,BOWLER,10.0,1300.0,KKR,Gujarat Titans
3,Rahul Tewatia,40 Lakh,ALL-ROUNDER,9.0,1170.0,RR,Gujarat Titans
4,Shubman Gill,Draft Pick,BATTER,8.0,1040.0,KKR,Gujarat Titans
...,...,...,...,...,...,...,...
628,Sairaj Patil,20 Lakh,BATTER,NaN,NaN,NaN,Unsold
629,Monu Singh,20 Lakh,BOWLER,NaN,NaN,NaN,Unsold
630,Nivethan Radhakrishnan,20 Lakh,BOWLER,NaN,NaN,NaN,Unsold
631,Lance Morris,20 Lakh,BOWLER,NaN,NaN,NaN,Unsold
632,Aaron Hardie,20 Lakh,ALL-ROUNDER,NaN,NaN,NaN,Unsold

# Checking the info()

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 633 entries, 0 to 632
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Player           633 non-null    object
 1   Base Price       633 non-null    object
 2   TYPE             633 non-null    object
 3   COST IN ₹ (CR.)  237 non-null    float64
 4   Cost IN $ (000)  237 non-null    float64
 5   2021 Squad       199 non-null    object
 6   Team             633 non-null    object
dtypes: float64(2), object(5)
memory usage: 39.6+ KB

# Summing up the last duplicated elements in Player series

In [5]:
df["Player"].duplicated(keep="last").sum()

4

# Summing up the last duplicated elements in TYPE series

In [6]:
df["TYPE"].duplicated(keep="last").sum()

629

# Summing up the last duplicated elements in COST IN ₹ (CR.) series

In [7]:
df["COST IN ₹ (CR.)"].duplicated(keep="last").sum()

567

# Dataframe of duplicated elements in Player series (keeping all)

In [8]:
df[df["Player"].duplicated(keep=False)]

,Player,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad,Team
62,Lalit Yadav,20 Lakh,ALL-ROUNDER,0.65,84.5,DC,Delhi Capitals
240,Amit Mishra,1.5 Cr,BOWLER,NaN,NaN,DC,Unsold
499,Amit Mishra,20 Lakh,BOWLER,NaN,NaN,NaN,Unsold
518,Shivam Sharma,20 Lakh,ALL-ROUNDER,NaN,NaN,NaN,Unsold
530,Lalit Yadav,20 Lakh,BOWLER,NaN,NaN,NaN,Unsold
537,Shubham Singh,20 Lakh,ALL-ROUNDER,NaN,NaN,NaN,Unsold
544,Shubham Singh,20 Lakh,BOWLER,NaN,NaN,NaN,Unsold
569,Shivam Sharma,20 Lakh,ALL-ROUNDER,NaN,NaN,NaN,Unsold

# Compairing the info() of full and duplicated dataframes

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 633 entries, 0 to 632
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Player           633 non-null    object
 1   Base Price       633 non-null    object
 2   TYPE             633 non-null    object
 3   COST IN ₹ (CR.)  237 non-null    float64
 4   Cost IN $ (000)  237 non-null    float64
 5   2021 Squad       199 non-null    object
 6   Team             633 non-null    object
dtypes: float64(2), object(5)
memory usage: 39.6+ KB

In [10]:
df[df["Player"].duplicated(keep="last")].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 62 to 537
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Player           4 non-null      object
 1   Base Price       4 non-null      object
 2   TYPE             4 non-null      object
 3   COST IN ₹ (CR.)  1 non-null      float64
 4   Cost IN $ (000)  1 non-null      float64
 5   2021 Squad       2 non-null      object
 6   Team             4 non-null      object
dtypes: float64(2), object(5)
memory usage: 256.0+ bytes

# Another way of producing dataframe of duplicated elements w.r.t particular series

In [11]:
df[df.duplicated(keep="first",subset=["Player"])]

,Player,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad,Team
499,Amit Mishra,20 Lakh,BOWLER,NaN,NaN,NaN,Unsold
530,Lalit Yadav,20 Lakh,BOWLER,NaN,NaN,NaN,Unsold
544,Shubham Singh,20 Lakh,BOWLER,NaN,NaN,NaN,Unsold
569,Shivam Sharma,20 Lakh,ALL-ROUNDER,NaN,NaN,NaN,Unsold