<a href="https://www.kaggle.com/shivavashishtha/l2-using-pd-read-csv-to-import-messy-csv-files?scriptVersionId=88480049" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Introduction 

Hi Folks,
We are starting the Full DataFlow Journey in which we are covering everything like ​​Importing Data, Cleaning Data, Merging, Joining, and Concatenating Data, GroupBy Operations, Reshaping and Pivoting DataFrames, Data Preparation and Feature Creation, etc.<br><br>

### Lecture Agenda
In this particular lecture we are going to learn how to read CSV files using pd.read_csv and clean it using pandas only


#### Technologies Used
Python, Pandas


### Data Used
Dirty Sales Data 
This dataset is uploaded by me on kaggle and the dataset is public to be used by anyone

### Getting Started

1. What is CSV File?
Add data files from kaggle <br>
CSV Files - A comma-separated values file is a delimited text file that uses a comma to separate values. Each line of the file is a data record. Each record consists of one or more fields, separated by commas. The use of the comma as a field separator is the source of the name for this file format.

2. Why to clean CSV files?
To get appropriate results, the data we are using has to be accurate. If, the data is not accurate it might result in wrong finding. So it is suggested to clean the data using different methods.

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/india-census-2001-districtwise/cencus.csv
/kaggle/input/meesy-csv/EQUITY_L.csv
/kaggle/input/dirty-data-sample/Ditry Data Sample.xlsx

In [2]:
#simply reading the file
df=pd.read_csv("../input/meesy-csv/EQUITY_L.csv")

In [3]:
df.head()

,,,,,,,,This,is,a file
SYMBOL,NAME OF COMPANY,SERIES,DATE OF LISTING,PAID UP VALUE,MARKET LOT,ISIN NUMBER,FACE VALUE,NaN,YahooEquiv,Yahoo_Equivalent_Code
20MICRONS,20 Microns Limited,EQ,06-Oct-08,5,1,INE144J01027,5,.NS,20MICRONS.NS,"'20MICRONS.NS',"
21STCENMGM,21st Century Management Services Limited,EQ,03-May-95,10,1,INE253B01015,10,.NS,21STCENMGM.NS,"'21STCENMGM.NS',"
3IINFOTECH,3i Infotech Limited,EQ,22-Apr-05,10,1,INE748C01020,10,.NS,3IINFOTECH.NS,"'3IINFOTECH.NS',"
3MINDIA,3M India Limited,EQ,13-Aug-04,10,1,INE470A01017,10,.NS,3MINDIA.NS,"'3MINDIA.NS',"

In [4]:
df.tail()

,,,,,,,,This,is,a file
ZOTA,Zota Health Care LImited,EQ,19-Aug-19,10,1,INE358U01012,10,.NS,ZOTA.NS,"'ZOTA.NS',"
ZUARI,Zuari Agro Chemicals Limited,EQ,27-Nov-12,10,1,INE840M01016,10,.NS,ZUARI.NS,"'ZUARI.NS',"
ZUARIGLOB,Zuari Global Limited,BE,12-Apr-95,10,1,INE217A01012,10,.NS,ZUARIGLOB.NS,"'ZUARIGLOB.NS',"
ZYDUSWELL,Zydus Wellness Limited,EQ,13-Nov-09,10,1,INE768C01010,10,.NS,ZYDUSWELL.NS,'ZYDUSWELL.NS'
This is the end of the file,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1667 entries, ('SYMBOL', 'NAME OF COMPANY', ' SERIES', ' DATE OF LISTING', ' PAID UP VALUE', ' MARKET LOT', ' ISIN NUMBER', ' FACE VALUE') to ('This is the end of the file', nan, nan, nan, nan, nan, nan, nan)
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   This     1665 non-null   object
 1    is      1666 non-null   object
 2    a file  1666 non-null   object
dtypes: object(3)
memory usage: 333.7+ KB

### Initial Inspection
From the initial insspection of the data, we can see the data is quite dirty. The header is not appropriate due to which we are not able to get the right finding.<br>
Our first step will include restting the header so that we can get better finding and understanding of the data

# 1st Approach 
* Setting header as index 1
* Dropping the last row

In [6]:
#resetting the header of the data to index 1
df=pd.read_csv("../input/meesy-csv/EQUITY_L.csv",header=1)

In [7]:
df

,SYMBOL,NAME OF COMPANY,SERIES,DATE OF LISTING,PAID UP VALUE,MARKET LOT,ISIN NUMBER,FACE VALUE,Unnamed: 8,YahooEquiv,Yahoo_Equivalent_Code
0,20MICRONS,20 Microns Limited,EQ,06-Oct-08,5.0,1.0,INE144J01027,5.0,.NS,20MICRONS.NS,"'20MICRONS.NS',"
1,21STCENMGM,21st Century Management Services Limited,EQ,03-May-95,10.0,1.0,INE253B01015,10.0,.NS,21STCENMGM.NS,"'21STCENMGM.NS',"
2,3IINFOTECH,3i Infotech Limited,EQ,22-Apr-05,10.0,1.0,INE748C01020,10.0,.NS,3IINFOTECH.NS,"'3IINFOTECH.NS',"
3,3MINDIA,3M India Limited,EQ,13-Aug-04,10.0,1.0,INE470A01017,10.0,.NS,3MINDIA.NS,"'3MINDIA.NS',"
4,3PLAND,3P Land Holdings Limited,EQ,19-Jul-95,2.0,1.0,INE105C01023,2.0,.NS,3PLAND.NS,"'3PLAND.NS',"
...,...,...,...,...,...,...,...,...,...,...,...
1661,ZOTA,Zota Health Care LImited,EQ,19-Aug-19,10.0,1.0,INE358U01012,10.0,.NS,ZOTA.NS,"'ZOTA.NS',"
1662,ZUARI,Zuari Agro Chemicals Limited,EQ,27-Nov-12,10.0,1.0,INE840M01016,10.0,.NS,ZUARI.NS,"'ZUARI.NS',"
1663,ZUARIGLOB,Zuari Global Limited,BE,12-Apr-95,10.0,1.0,INE217A01012,10.0,.NS,ZUARIGLOB.NS,"'ZUARIGLOB.NS',"
1664,ZYDUSWELL,Zydus Wellness Limited,EQ,13-Nov-09,10.0,1.0,INE768C01010,10.0,.NS,ZYDUSWELL.NS,'ZYDUSWELL.NS'
1665,This is the end of the file,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
#As I can see the last line is also not corrupted, So we are dropping the last line of the data
df.drop(index=1665,axis=0)

,SYMBOL,NAME OF COMPANY,SERIES,DATE OF LISTING,PAID UP VALUE,MARKET LOT,ISIN NUMBER,FACE VALUE,Unnamed: 8,YahooEquiv,Yahoo_Equivalent_Code
0,20MICRONS,20 Microns Limited,EQ,06-Oct-08,5.0,1.0,INE144J01027,5.0,.NS,20MICRONS.NS,"'20MICRONS.NS',"
1,21STCENMGM,21st Century Management Services Limited,EQ,03-May-95,10.0,1.0,INE253B01015,10.0,.NS,21STCENMGM.NS,"'21STCENMGM.NS',"
2,3IINFOTECH,3i Infotech Limited,EQ,22-Apr-05,10.0,1.0,INE748C01020,10.0,.NS,3IINFOTECH.NS,"'3IINFOTECH.NS',"
3,3MINDIA,3M India Limited,EQ,13-Aug-04,10.0,1.0,INE470A01017,10.0,.NS,3MINDIA.NS,"'3MINDIA.NS',"
4,3PLAND,3P Land Holdings Limited,EQ,19-Jul-95,2.0,1.0,INE105C01023,2.0,.NS,3PLAND.NS,"'3PLAND.NS',"
...,...,...,...,...,...,...,...,...,...,...,...
1660,ZODJRDMKJ,Zodiac JRD- MKJ Limited,EQ,19-Jul-95,10.0,1.0,INE077B01018,10.0,.NS,ZODJRDMKJ.NS,"'ZODJRDMKJ.NS',"
1661,ZOTA,Zota Health Care LImited,EQ,19-Aug-19,10.0,1.0,INE358U01012,10.0,.NS,ZOTA.NS,"'ZOTA.NS',"
1662,ZUARI,Zuari Agro Chemicals Limited,EQ,27-Nov-12,10.0,1.0,INE840M01016,10.0,.NS,ZUARI.NS,"'ZUARI.NS',"
1663,ZUARIGLOB,Zuari Global Limited,BE,12-Apr-95,10.0,1.0,INE217A01012,10.0,.NS,ZUARIGLOB.NS,"'ZUARIGLOB.NS',"
1664,ZYDUSWELL,Zydus Wellness Limited,EQ,13-Nov-09,10.0,1.0,INE768C01010,10.0,.NS,ZYDUSWELL.NS,'ZYDUSWELL.NS'

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1666 entries, 0 to 1665
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SYMBOL                 1666 non-null   object
 1   NAME OF COMPANY        1665 non-null   object
 2    SERIES                1665 non-null   object
 3    DATE OF LISTING       1665 non-null   object
 4    PAID UP VALUE         1665 non-null   float64
 5    MARKET LOT            1665 non-null   float64
 6    ISIN NUMBER           1665 non-null   object
 7    FACE VALUE            1665 non-null   float64
 8   Unnamed: 8             1665 non-null   object
 9   YahooEquiv             1665 non-null   object
 10  Yahoo_Equivalent_Code  1665 non-null   object
dtypes: float64(3), object(8)
memory usage: 143.3+ KB

In [10]:
df.isnull().sum()

SYMBOL                   0
NAME OF COMPANY          1
 SERIES                  1
 DATE OF LISTING         1
 PAID UP VALUE           1
 MARKET LOT              1
 ISIN NUMBER             1
 FACE VALUE              1
Unnamed: 8               1
YahooEquiv               1
Yahoo_Equivalent_Code    1
dtype: int64

In [11]:
df.columns

Index(['SYMBOL', 'NAME OF COMPANY', ' SERIES', ' DATE OF LISTING',
       ' PAID UP VALUE', ' MARKET LOT', ' ISIN NUMBER', ' FACE VALUE',
       'Unnamed: 8', 'YahooEquiv', 'Yahoo_Equivalent_Code'],
      dtype='object')

# 2nd Approach 
* Performing all operations while reading the Data
* Skipping 2 top rows
* Skipping 1 row from footer
* Setting header to None
* Setting up column names manually

In [12]:
col_names=['SYMBOL', 'NAME OF COMPANY', ' SERIES', ' DATE OF LISTING',
       ' PAID UP VALUE', ' MARKET LOT', ' ISIN NUMBER', ' FACE VALUE',
       'Unnamed: 8', 'YahooEquiv', 'Yahoo_Equivalent_Code']

In [13]:
df2=pd.read_csv("../input/meesy-csv/EQUITY_L.csv",skiprows=2,skipfooter=1,header=None,names=col_names)

/opt/conda/lib/python3.7/site-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)

In [14]:
df2

,SYMBOL,NAME OF COMPANY,SERIES,DATE OF LISTING,PAID UP VALUE,MARKET LOT,ISIN NUMBER,FACE VALUE,Unnamed: 8,YahooEquiv,Yahoo_Equivalent_Code
0,20MICRONS,20 Microns Limited,EQ,06-Oct-08,5,1,INE144J01027,5,.NS,20MICRONS.NS,"'20MICRONS.NS',"
1,21STCENMGM,21st Century Management Services Limited,EQ,03-May-95,10,1,INE253B01015,10,.NS,21STCENMGM.NS,"'21STCENMGM.NS',"
2,3IINFOTECH,3i Infotech Limited,EQ,22-Apr-05,10,1,INE748C01020,10,.NS,3IINFOTECH.NS,"'3IINFOTECH.NS',"
3,3MINDIA,3M India Limited,EQ,13-Aug-04,10,1,INE470A01017,10,.NS,3MINDIA.NS,"'3MINDIA.NS',"
4,3PLAND,3P Land Holdings Limited,EQ,19-Jul-95,2,1,INE105C01023,2,.NS,3PLAND.NS,"'3PLAND.NS',"
...,...,...,...,...,...,...,...,...,...,...,...
1660,ZODJRDMKJ,Zodiac JRD- MKJ Limited,EQ,19-Jul-95,10,1,INE077B01018,10,.NS,ZODJRDMKJ.NS,"'ZODJRDMKJ.NS',"
1661,ZOTA,Zota Health Care LImited,EQ,19-Aug-19,10,1,INE358U01012,10,.NS,ZOTA.NS,"'ZOTA.NS',"
1662,ZUARI,Zuari Agro Chemicals Limited,EQ,27-Nov-12,10,1,INE840M01016,10,.NS,ZUARI.NS,"'ZUARI.NS',"
1663,ZUARIGLOB,Zuari Global Limited,BE,12-Apr-95,10,1,INE217A01012,10,.NS,ZUARIGLOB.NS,"'ZUARIGLOB.NS',"
1664,ZYDUSWELL,Zydus Wellness Limited,EQ,13-Nov-09,10,1,INE768C01010,10,.NS,ZYDUSWELL.NS,'ZYDUSWELL.NS'

In [15]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1665 entries, 0 to 1664
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SYMBOL                 1665 non-null   object
 1   NAME OF COMPANY        1665 non-null   object
 2    SERIES                1665 non-null   object
 3    DATE OF LISTING       1665 non-null   object
 4    PAID UP VALUE         1665 non-null   int64
 5    MARKET LOT            1665 non-null   int64
 6    ISIN NUMBER           1665 non-null   object
 7    FACE VALUE            1665 non-null   int64
 8   Unnamed: 8             1665 non-null   object
 9   YahooEquiv             1665 non-null   object
 10  Yahoo_Equivalent_Code  1665 non-null   object
dtypes: int64(3), object(8)
memory usage: 143.2+ KB

In [16]:
df2.columns

Index(['SYMBOL', 'NAME OF COMPANY', ' SERIES', ' DATE OF LISTING',
       ' PAID UP VALUE', ' MARKET LOT', ' ISIN NUMBER', ' FACE VALUE',
       'Unnamed: 8', 'YahooEquiv', 'Yahoo_Equivalent_Code'],
      dtype='object')