# Introduction 

Hi Folks,
We are starting the Full DataFlow Journey in which we are covering everything like ​​Importing Data, Cleaning Data, Merging, Joining, and Concatenating Data, GroupBy Operations, Reshaping and Pivoting DataFrames, Data Preparation and Feature Creation, etc.<br><br>

### Lecture Agenda
In this particular lecture we are going to learn how to read jtml files using pd.read_html and clean it using pandas only. Reading data from the web has it's own domain known as data scraping. In this lecture we are going to touch the surface of Data Scraping.


#### Technologies Used
Python, Pandas


### Data Used
List of countries by GDP (nominal)
Sorce : wikipedia

### Getting Started

1. Why to scrap Data?
The internet is a pool of data and, with the right set of skills, one can use this data in a way to gain a lot of new information. You can always copy paste the data to your excel or CSV file but that is also time-consuming and expensive. Why not hire a software developer who can get the data into a readable format by writing some jiber-jabber? Yes, it is possible to extract data from Web and this "jibber-jabber" is called Web Scraping.

2. Why to clean fetched files?
As said earlier Internet is a pool of Data, when we'll be willing to fetch some speccific data from the web it is not always going to happen that we'll be getting the specific data we want. However, we'll having a lot unwanted dat which need to be cleaned.

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
#fixing the url from where we want to fetch the data
url="https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)"

In [3]:
#simply fetch the html data using read_html
df=pd.read_html(url)

In [4]:
#let's have a look at the data we have got
df

[                                             0
 0  Largest economies by nominal GDP in 2021[1],
                                                    0  \
 0  .mw-parser-output .legend{page-break-inside:av...

                                                    1  \
 0  $750 billion – $1 trillion $500–750 billion $2...

                                                    2
 0  $50–100 billion $25–50 billion $5–25 billion <...  ,
     Country/Territory    Region      IMF[1]            United Nations[12]  \
     Country/Territory    Region    Estimate       Year           Estimate
 0       United States  Americas  22939580.0       2021         20893746.0
 1               China      Asia  16862979.0  [n 2]2021         14722801.0
 2               Japan      Asia   5103110.0       2021          5057759.0
 3             Germany    Europe   4230172.0       2021          3846414.0
 4      United Kingdom    Europe   3108416.0       2021          2764198.0
 ..                ...       ...         ...        ...                ...
 211          Kiribati   Oceania       232.0       2021              181.0
 212             Palau   Oceania       208.0       2021              264.0
 213             Nauru   Oceania       133.0       2021              135.0
 214        Montserrat  Americas         NaN        NaN               68.0
 215            Tuvalu   Oceania        65.0       2021               55.0

                World Bank[13][14]
           Year           Estimate  Year
 0         2020         20936600.0  2020
 1    [n 3]2020         14722731.0  2020
 2         2020          4975415.0  2020
 3         2020          3806060.0  2020
 4         2020          2707744.0  2020
 ..         ...                ...   ...
 211       2020              200.0  2020
 212       2020              268.0  2019
 213       2020              118.0  2019
 214       2020                NaN   NaN
 215       2020               49.0  2020

 [216 rows x 8 columns],
   .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}vteLists of countries by financial rankings  \
 0                                              Trade
 1                                         Investment
 2                                              Funds
 3                                    Budget and debt
 4                                   Income and taxes
 5                                         Bank rates
 6                                           Currency
 7                                              Other
 8  Lists of countries by GDP rankings List of int...

   .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}vteLists of countries by financial rankings.1
 0  Account balance % of GDP Exports net per capit...
 1                   FDI received past FDI abroad GFI
 2  Forex reserves Forex reserves (ex. gold) Gold ...
 3  Government budget PPP % of GDP per capita Cred...
 4  Tax rates Inheritance tax Tax revenue Wage ave...
 5  Central bank interest rate Commercial bank pri...
 6               Exchange rates to US$ Inflation rate
 7  Financial Development Index Corporate governan...
 8  Lists of countries by GDP rankings List of int...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ,
                vteLists of countries by GDP rankings  \
 0                                            Nominal
 1                       Purchasing power parity(PPP)
 2                                        Growth rate
 3                        Gross national income (GNI)
 4                                Countries by region
 5                              Subnational divisions
 6  Lists of countries by financial rankings List ...

              vteLists of countries by GDP rankings.1
 0  Per capita Past and projected per capita Secto...
 1  Per capita Past per capita Past and projected ...
 2  African countries Asian states European Union ...
 3                  PPP per capita Nominal per capita
 4  Africa PPP nominal Commonwealth of Nations PPP...
 5  Albania Argentina Australia Austria Belarus Be...
 6  Lists of countries by financial rankings List ...  ,
               vteEconomic classification of countries  \
 0   Developed country Developing country Least dev...
 1                                   Three-World Model
 2                        Gross domestic product (GDP)
 3                                             Nominal
 4                       Purchasing power parity (PPP)
 5                         Gross national income (GNI)
 6                                               Wages
 7                                              Wealth
 8                             Other national accounts
 9                                   Human development
 10                                     Digital divide
 11       Net international investment position (NIIP)
 12                    Economics portal • World portal

             vteEconomic classification of countries.1
 0   Developed country Developing country Least dev...
 1   First World Second World Third World Fourth World
 2   Nominal By country past and projected per capi...
 3   By country past and projected per capita per c...
 4   By country future estimates per capita per cap...
 5   (Nominal, Atlas method) per capita (PPP) per c...
 6   Average wage Europe Employee compensation (per...
 7   Wealth per adult Europe Financial assets per c...
 8   Gross National Happiness Net material product ...
 9   Human Development Index by country inequality-...
 10  ICT Development Index Number of broadband Inte...
 11        Per capita (creditors) Per capita (debtors)
 12                    Economics portal • World portal  ,
                                0  \
 0                        Nominal
 1  Purchasing power parity (PPP)

                                                    1
 0  By country past and projected per capita per c...
 1  By country future estimates per capita per cap...  ]

In [5]:
#Dosen't look like a dataframe to me, let's check the type 
type(df)

list

In [6]:
#Alright, It is fetched as a List, let's fetch using indexing
df[2]

    Country/Territory    Region      IMF[1]            United Nations[12]  \
    Country/Territory    Region    Estimate       Year           Estimate
0       United States  Americas  22939580.0       2021         20893746.0
1               China      Asia  16862979.0  [n 2]2021         14722801.0
2               Japan      Asia   5103110.0       2021          5057759.0
3             Germany    Europe   4230172.0       2021          3846414.0
4      United Kingdom    Europe   3108416.0       2021          2764198.0
..                ...       ...         ...        ...                ...
211          Kiribati   Oceania       232.0       2021              181.0
212             Palau   Oceania       208.0       2021              264.0
213             Nauru   Oceania       133.0       2021              135.0
214        Montserrat  Americas         NaN        NaN               68.0
215            Tuvalu   Oceania        65.0       2021               55.0

               World Bank[13][14]
          Year           Estimate  Year
0         2020         20936600.0  2020
1    [n 3]2020         14722731.0  2020
2         2020          4975415.0  2020
3         2020          3806060.0  2020
4         2020          2707744.0  2020
..         ...                ...   ...
211       2020              200.0  2020
212       2020              268.0  2019
213       2020              118.0  2019
214       2020                NaN   NaN
215       2020               49.0  2020

[216 rows x 8 columns]

In [7]:
#we have got the right dataframe at index 2 
#let's create a new dataframe using that index
df1=df[2]

In [8]:
#checking the dataframe again
df1

    Country/Territory    Region      IMF[1]            United Nations[12]  \
    Country/Territory    Region    Estimate       Year           Estimate
0       United States  Americas  22939580.0       2021         20893746.0
1               China      Asia  16862979.0  [n 2]2021         14722801.0
2               Japan      Asia   5103110.0       2021          5057759.0
3             Germany    Europe   4230172.0       2021          3846414.0
4      United Kingdom    Europe   3108416.0       2021          2764198.0
..                ...       ...         ...        ...                ...
211          Kiribati   Oceania       232.0       2021              181.0
212             Palau   Oceania       208.0       2021              264.0
213             Nauru   Oceania       133.0       2021              135.0
214        Montserrat  Americas         NaN        NaN               68.0
215            Tuvalu   Oceania        65.0       2021               55.0

               World Bank[13][14]
          Year           Estimate  Year
0         2020         20936600.0  2020
1    [n 3]2020         14722731.0  2020
2         2020          4975415.0  2020
3         2020          3806060.0  2020
4         2020          2707744.0  2020
..         ...                ...   ...
211       2020              200.0  2020
212       2020              268.0  2019
213       2020              118.0  2019
214       2020                NaN   NaN
215       2020               49.0  2020

[216 rows x 8 columns]

In [9]:
#checking the shape
df1.shape

(216, 8)

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   (Country/Territory, Country/Territory)  216 non-null    object
 1   (Region, Region)                        216 non-null    object
 2   (IMF[1], Estimate)                      196 non-null    float64
 3   (IMF[1], Year)                          196 non-null    object
 4   (United Nations[12], Estimate)          213 non-null    float64
 5   (United Nations[12], Year)              213 non-null    object
 6   (World Bank[13][14], Estimate)          210 non-null    float64
 7   (World Bank[13][14], Year)              210 non-null    object
dtypes: float64(3), object(5)
memory usage: 13.6+ KB

In [11]:
df1.isnull().sum()

Country/Territory   Country/Territory     0
Region              Region                0
IMF[1]              Estimate             20
                    Year                 20
United Nations[12]  Estimate              3
                    Year                  3
World Bank[13][14]  Estimate              6
                    Year                  6
dtype: int64

# Conclusion 
We have successfully the Data from the web. Now we can perform the operations we want using this Data