In [1]:
##### This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Stock Split and Dividends by YFinance
These type of data can also be fetched using yfinance library by setting actions argument true<br><br>
**actions: bool**
* Download dividend + stock splits data. Default is False

In [2]:
#installing the library
!pip install yfinance

Collecting yfinance
  Downloading yfinance-0.1.70-py2.py3-none-any.whl (26 kB)
Collecting multitasking>=0.0.7
  Downloading multitasking-0.0.10.tar.gz (8.2 kB)
  Preparing metadata (setup.py) ... - done
Requirement already satisfied: pandas>=0.24.0 in /opt/conda/lib/python3.7/site-packages (from yfinance) (1.3.5)
Requirement already satisfied: lxml>=4.5.1 in /opt/conda/lib/python3.7/site-packages (from yfinance) (4.8.0)
Requirement already satisfied: numpy>=1.15 in /opt/conda/lib/python3.7/site-packages (from yfinance) (1.20.3)
Requirement already satisfied: requests>=2.26 in /opt/conda/lib/python3.7/site-packages (from yfinance) (2.26.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.7/site-packages (from pandas>=0.24.0->yfinance) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.7/site-packages (from pandas>=0.24.0->yfinance) (2021.3)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests>=2.26->yfinance) (3.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/conda/lib/python3.7/site-packages (from requests>=2.26->yfinance) (2.0.9)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from requests>=2.26->yfinance) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests>=2.26->yfinance) (2021.10.8)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->yfinance) (1.16.0)
Building wheels for collected packages: multitasking
  Building wheel for multitasking (setup.py) ... - \ done
  Created wheel for multitasking: filename=multitasking-0.0.10-py3-none-any.whl size=8500 sha256=a3d676c2d5e9eed6922e6e20b0d255a71165717924d8a4872cfffaac405dceb6
  Stored in directory: /root/.cache/pip/wheels/34/ba/79/c0260c6f1a03f420ec7673eff9981778f293b9107974679e36
Successfully built multitasking
Installing collected packages: multitasking, yfinance
Successfully installed multitasking-0.0.10 yfinance-0.1.70
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [3]:
#importing the library in the environment
import yfinance as yf

In [4]:
#setting the ticker
ticker="aapl"

In [5]:
#creating a dataframe by fetching the data 
df=yf.download(ticker,period="10y",actions=True)

[*********************100%***********************]  1 of 1 completed

In [6]:
#checking the dataframe
df

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
2012-04-09,22.361786,22.851429,22.332144,22.722500,19.456697,597536800,0.0,0.0
2012-04-10,22.854643,23.000000,22.357143,22.444286,19.218468,889725200,0.0,0.0
2012-04-11,22.721430,22.745358,22.262142,22.364286,19.149967,696614800,0.0,0.0
2012-04-12,22.321428,22.547501,22.160713,22.241785,19.045074,614336800,0.0,0.0
2012-04-13,22.289642,22.310715,21.553928,21.615356,18.508675,859644800,0.0,0.0
...,...,...,...,...,...,...,...,...
2022-04-01,174.029999,174.880005,171.940002,174.309998,174.309998,78699800,0.0,0.0
2022-04-04,174.570007,178.490005,174.440002,178.440002,178.440002,76468400,0.0,0.0
2022-04-05,177.500000,178.300003,174.419998,175.059998,175.059998,73401800,0.0,0.0
2022-04-06,172.360001,173.630005,170.130005,171.830002,171.830002,89058800,0.0,0.0
2022-04-07,171.160004,173.360001,169.850006,172.139999,172.139999,77517700,0.0,0.0

In [7]:
#checking the info
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2518 entries, 2012-04-09 to 2022-04-07
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          2518 non-null   float64
 1   High          2518 non-null   float64
 2   Low           2518 non-null   float64
 3   Close         2518 non-null   float64
 4   Adj Close     2518 non-null   float64
 5   Volume        2518 non-null   int64
 6   Dividends     2518 non-null   float64
 7   Stock Splits  2518 non-null   float64
dtypes: float64(7), int64(1)
memory usage: 177.0 KB

In [8]:
df.columns

Index(['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume', 'Dividends',
       'Stock Splits'],
      dtype='object')

In [9]:
#producing a dataframe with dividend values of more than 0
df[df.Dividends>0]

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
2012-08-09,22.066071,22.204643,22.064285,22.168928,19.064190,221642400,0.094643,0.0
2012-11-07,20.494286,20.519285,19.848213,19.928572,17.215866,793648800,0.094643,0.0
2013-02-07,16.544643,16.785713,16.218571,16.722143,14.530094,704580800,0.094643,0.0
2013-05-09,16.421785,16.535713,16.270714,16.313213,14.268591,398487600,0.108929,0.0
2013-08-08,16.566429,16.575001,16.355356,16.464643,14.496126,255777200,0.108929,0.0
2013-11-06,18.719643,18.745001,18.507143,18.604286,16.475588,223375600,0.108929,0.0
2014-02-06,18.216429,18.339287,18.136070,18.303928,16.306622,257765200,0.108929,0.0
2014-05-08,21.008928,21.228930,20.942858,20.999643,18.812670,230297200,0.117500,0.0
2014-08-07,23.732500,23.987499,23.525000,23.620001,21.265396,186844000,0.117500,0.0
2014-11-06,27.150000,27.197500,26.950001,27.174999,24.572092,139874000,0.117500,0.0
2015-02-05,30.004999,30.057501,29.812500,29.985001,27.219944,168984800,0.117500,0.0
2015-05-07,31.192499,31.520000,31.004999,31.315001,28.546045,175763600,0.130000,0.0
2015-08-06,28.992500,29.125000,28.530001,28.782499,26.356234,211612000,0.130000,0.0
2015-11-05,30.462500,30.672501,30.045000,30.230000,27.800211,158210800,0.130000,0.0
2016-02-04,23.965000,24.332500,23.797501,24.150000,22.329418,185886800,0.130000,0.0
2016-05-05,23.500000,23.517500,23.170000,23.309999,21.683960,143562000,0.142500,0.0
2016-08-04,26.395000,26.500000,26.320000,26.467501,24.754581,109634800,0.142500,0.0
2016-11-03,27.745001,27.865000,27.387501,27.457500,25.812361,107730400,0.142500,0.0
2017-02-09,32.912498,33.112499,32.779999,33.105000,31.256413,113399600,0.142500,0.0
2017-05-11,38.112499,38.517502,38.077499,38.487499,36.488346,109020400,0.157500,0.0
2017-08-10,39.974998,40.000000,38.657501,38.830002,36.957623,163217200,0.157500,0.0
2017-11-10,43.777500,43.845001,43.567501,43.667500,41.711258,100582000,0.157500,0.0
2018-02-09,39.267502,39.472500,37.560001,39.102501,37.503056,282690400,0.157500,0.0
2018-05-11,47.372501,47.514999,46.862499,47.147499,45.393349,104848800,0.182500,0.0
2018-08-10,51.840000,52.275002,51.667500,51.882500,50.127365,98444800,0.182500,0.0
2018-11-08,52.494999,52.529999,51.687500,52.122501,50.534962,101450400,0.182500,0.0
2019-02-08,42.247501,42.665001,42.105000,42.602501,41.482059,95280000,0.182500,0.0
2019-05-10,49.355000,49.712502,48.192501,49.294998,48.183392,164834800,0.192500,0.0
2019-08-09,50.325001,50.689999,49.822498,50.247501,49.301029,98478800,0.192500,0.0
2019-11-07,64.684998,65.087502,64.527496,64.857498,63.826889,94940400,0.192500,0.0
2020-02-07,80.592499,80.849998,79.500000,80.007500,78.923012,117684000,0.192500,0.0
2020-05-08,76.410004,77.587502,76.072502,77.532501,76.688599,133838400,0.205000,0.0
2020-08-07,113.205002,113.675003,110.292503,111.112503,110.101250,198045600,0.205000,0.0
2020-11-06,118.320000,119.199997,116.129997,118.690002,117.812683,114457900,0.205000,0.0
2021-02-05,137.350006,137.419998,135.860001,136.759995,135.951950,75693800,0.205000,0.0
2021-05-07,130.850006,131.259995,129.479996,130.210007,129.660553,78973300,0.220000,0.0
2021-08-06,146.350006,147.110001,145.630005,146.139999,145.741333,54126800,0.220000,0.0
2021-11-05,151.889999,152.199997,150.059998,151.279999,151.087509,65463900,0.220000,0.0
2022-02-04,171.679993,174.100006,170.679993,172.389999,172.389999,82465400,0.220000,0.0

In [10]:
#checking the data of specific range 
df.loc["2012-08-05":"2012-08-15"]

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
2012-08-06,22.046070,22.316786,21.973572,22.233929,19.038338,302103200,0.000000,0.0
2012-08-07,22.241785,22.321428,22.072857,22.175358,18.988188,290446800,0.000000,0.0
2012-08-08,22.121071,22.281429,22.039286,22.137857,18.956078,244706000,0.000000,0.0
2012-08-09,22.066071,22.204643,22.064285,22.168928,19.064190,221642400,0.094643,0.0
2012-08-10,22.096786,22.205713,22.096430,22.203571,19.093979,194938800,0.000000,0.0
2012-08-13,22.263929,22.500000,22.258928,22.500000,19.348892,278832400,0.000000,0.0
2012-08-14,22.566786,22.807501,22.507500,22.560356,19.400795,340169200,0.000000,0.0
2012-08-15,22.546429,22.642857,22.419643,22.529642,19.374386,257342400,0.000000,0.0

In [11]:
df.loc["2012-08-05":"2012-08-15"].diff()

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
2012-08-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2012-08-07,0.195715,0.004642,0.099285,-0.058571,-0.050150,-11656400.0,0.000000,0.0
2012-08-08,-0.120714,-0.039999,-0.033571,-0.037500,-0.032110,-45740800.0,0.000000,0.0
2012-08-09,-0.055000,-0.076786,0.025000,0.031071,0.108112,-23063600.0,0.094643,0.0
2012-08-10,0.030716,0.001070,0.032145,0.034643,0.029789,-26703600.0,-0.094643,0.0
2012-08-13,0.167143,0.294287,0.162498,0.296429,0.254913,83893600.0,0.000000,0.0
2012-08-14,0.302856,0.307501,0.248571,0.060356,0.051903,61336800.0,0.000000,0.0
2012-08-15,-0.020357,-0.164644,-0.087856,-0.030714,-0.026409,-82826800.0,0.000000,0.0

In [12]:
#producing a dataframe with stock splits values of more than 0
df[df["Stock Splits"]>0]

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
2014-06-09,23.174999,23.469999,22.9375,23.424999,20.985443,301660000,0.0,7.0
2020-08-31,127.580002,131.000000,126.0000,129.039993,127.865585,225702700,0.0,4.0